### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by garnetwzy** [luohui8891/myhtmlapp#1]
想问一下这个SDWebImage的[SDWebImageDownloaderOperation start] crash的问题您知道怎么复现吗？或是在什么情况下才能复现啊，非常抱歉打扰您了

https://github.com/rs/SDWebImage/issues/691

**Comment by luohui8891** [comment]
@garnetwzy 不知道诶。我们是fabric上统计拿到的。我们本地不能复现这个bug。
BTW, 你可以直接在那个issue下面回复我呀，为什么要跑到这里来发一个。囧。
